"""adicao do atributo fonte na entidade Autobiografia

Revision ID: 623e3d3d26c0
Revises: 
Create Date: 2022-01-18 16:14:00.350521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e3d3d26c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autobiografia', sa.Column('fonte', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autobiografia', 'fonte')
    # ### end Alembic commands ###
