"""primeira migracao

Revision ID: 44d87da3a571
Revises: 
Create Date: 2022-01-21 21:08:30.783851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d87da3a571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('autobiografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=20000), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autobiografia')
    op.drop_table('usuario')
    # ### end Alembic commands ###
